@echo off
mode co80
echo                    ษออออออออออออออออออออออออออออออออออออออป
echo                    บ         *** Little Willy ***         ฬอป
echo                    บ (c) 1993 by I. Mustun / Dimension 16 บ บ
echo                    บ              & M.B. Soft             บ บ
echo                    บ                                      บ บ
echo                    บ THIS IS  N O T  S H A R E W A R E  ! บ บ
echo                    บ                                      บ บ
echo                    บ   Little Willy v1.1 is loading ...   บ บ
echo                    ศอหออออออออออออออออออออออออออออออออออออผ บ
echo                      ศออออออออออออออออออออออออออออออออออออออผ
lw5.exe
